### ISSUE TITLE
Configure modules error 500

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#1095]
When pressing Mod-Config on the news i get error 500
Url: https://www.netsession.net/index.php?mod=install&action=mod_cfg&module=news

Apache error log
```
<html>
<body>
<!--StartFragment-->
2024-04-10 18:22:49 | Error | 500 | GET /index.php?mod=install&action=mod_cfg&module=news HTTP/1.0 |   |   | 916 | SSL/TLS-Zugriff für Apache
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-04-10 18:22:50 | Error | 500 | GET /index.php?mod=install&action=mod_cfg&module=news HTTP/1.0 |   |   | 916 | SSL/TLS-Zugriff für Apache
```
As well on Mod-Config from the Parties
URL: https://www.netsession.net/index.php?mod=install&action=mod_cfg&module=party

Apache error log
```
<!--StartFragment-->
2024-04-10 18:31:32 | Error |  | 500 | GET /index.php?mod=install&action=mod_cfg&module=party HTTP/1.0
-- | -- | -- | -- | --

<!--EndFragment-->
```

Module seating as well
URL: https://www.netsession.net/index.php?mod=install&action=mod_cfg&module=seating

Apache error log
```
<!--StartFragment-->
2024-04-10 18:33:24 | Error | | 500 | GET /index.php?mod=install&action=mod_cfg&module=seating HTTP/1.0
-- | -- | -- | -- | --


<!--EndFragment-->
```

Und viele wietere Module, ich click ejetzt nicht explicit alle durch ;-)

**Comment by M4LuZ** [comment]
Hi @Pimmal,

this is is most probably related and caused by the issues noted in  #1096.
I suggest to run a Git + DB upgrade and then see if the issue disappears.

**Comment by Pimmal** [comment]
I updated to the latest master branch, I also made the configuration wizard and still error 500

```
2024-04-25 23:46:55	Error	xxx	500	GET /index.php?mod=install&action=mod_cfg&module=tournament2 HTTP/1.0	https://netsession.net/	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0	916	SSL/TLS-Zugriff für Apache
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: PHP Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-lansuite LIKE 'ls_t2_games'' at line 1 in /netsession.net/httpdocs/inc/Classes/DB.php:213, referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: Stack trace:, referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #0 /netsession.net/httpdocs/inc/Classes/DB.php(213): mysqli_query(), referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #1 /netsession.net/httpdocs/inc/Classes/DB.php(349): LanSuite\\DB->qry(), referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #2 /netsession.net/httpdocs/modules/install/mod_cfg.php(233): LanSuite\\DB->qry_first(), referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #3 /netsession.net/httpdocs/index_module.inc.php(108): include_once('/var/www/vhosts...'), referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #4 /netsession.net/httpdocs/index.php(461): include_once('/var/www/vhosts...'), referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #5 {main}, referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: thrown in /netsession.net/httpdocs/inc/Classes/DB.php on line 213, referer: https://netsession.net/				Apache-Fehler
```

![image](https://github.com/lansuite/lansuite/assets/20731374/19e99d76-989e-410f-8965-f386153d9c1d)

**Comment by M4LuZ** [comment]
> I updated to the latest master branch, I also made the configuration wizard and still error 500

I have a good idea where that is coming from. 
What is the name of the MySQL-database that you are using?
Appears to be _something_-lansuite?
