### ISSUE TITLE
Apache errors and warnings

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#1096]
When opening our site i get the following Apache errors in the log.
```
<html>
<body>
<!--StartFragment-->
2024-04-10 18:26:25 | Error |  | 500 | GET /index.php?mod=shoutbox&frmwrkmode=ajax&action=shoutqueries&shout=view&lastid=0&time=1712766384259 HTTP/1.0 |   |   | 916 | SSL/TLS-Zugriff für Apache
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: PHP Warning: Undefined array key "charset" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/DB.php on line 113, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: PHP Warning: Undefined array key "mod" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Security.php on line 29, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: PHP Warning: Undefined array key "action" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Security.php on line 30, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: PHP Warning: Undefined array key "step" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Security.php on line 31, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: PHP Fatal error: Uncaught mysqli_sql_exception: Unknown column 'error_runs' in 'field list' in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Database.php:192, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: Stack trace:, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #0 /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Database.php(192): mysqli->prepare(), referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #1 /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Database.php(234): LanSuite\\Database->query(), referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #2 /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/modules/cron2/Classes/Cron2.php(25): LanSuite\\Database->queryWithOnlyFirstRow(), referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #3 /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/modules/cron2/Classes/Cron2.php(98): LanSuite\\Module\\Cron2\\Cron2->Run(), referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #4 /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/index.php(504): LanSuite\\Module\\Cron2\\Cron2->CheckJobs(), referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #5 {main}, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: thrown in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Database.php on line 192, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: PHP Warning: Undefined array key "charset" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/DB.php on line 113, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: PHP Warning: Undefined array key "step" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Security.php on line 31, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: PHP Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE sessid = ?' at line 1 in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Database.php:192, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: Stack trace:, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #0 /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Database.php(192): mysqli->prepare(), referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #1 /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Auth.php(690): LanSuite\\Database->query(), referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #2 /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Auth.php(108): LanSuite\\Auth->update_visits(), referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #3 /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/index.php(348): LanSuite\\Auth->__construct(), referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: #4 {main}, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler
2024-04-10 18:26:25 | Warning |   |   | mod_fcgid: stderr: thrown in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/Database.php on line 192, referer: https://www.netsession.net/ |   |   |   | Apache-Fehler

<!--EndFragment-->
```

**Comment by M4LuZ** [comment]
Hi @Pimmal:
it appears that your installation is at least missing one db structure change in regards to cron2 (see #926).
that explains the error `Unknown column 'error_runs' in 'field list'`

Either just run update that module (there is now an option for that in the module list) or for all of them.
If you are not able to access the page (due to cron being executed regularly) then running through the wizzard should also do the trick, see https://lansuite.github.io/lansuite/docs/guides/upgrade/#configuration-environmentconfigured
Be aware that a fix for an update issue was merged just yesterday, so upgrade master first (#1112)

Issue in  `Classes/Security.php on line 31` was solved in #1101, so upgrading may also solve the other issues that you noticed

**Comment by Pimmal** [comment]
I updated to the latest master branch, I also made the configuration wizard and still error 500

```
2024-04-25 23:46:55	Error	xxx	500	GET /index.php?mod=install&action=mod_cfg&module=tournament2 HTTP/1.0	https://netsession.net/	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0	916	SSL/TLS-Zugriff für Apache
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: PHP Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-lansuite LIKE 'ls_t2_games'' at line 1 in /netsession.net/httpdocs/inc/Classes/DB.php:213, referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: Stack trace:, referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #0 /netsession.net/httpdocs/inc/Classes/DB.php(213): mysqli_query(), referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #1 /netsession.net/httpdocs/inc/Classes/DB.php(349): LanSuite\\DB->qry(), referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #2 /netsession.net/httpdocs/modules/install/mod_cfg.php(233): LanSuite\\DB->qry_first(), referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #3 /netsession.net/httpdocs/index_module.inc.php(108): include_once('/var/www/vhosts...'), referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #4 /netsession.net/httpdocs/index.php(461): include_once('/var/www/vhosts...'), referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: #5 {main}, referer: https://netsession.net/				Apache-Fehler
2024-04-25 23:46:55	Warning	xxx		mod_fcgid: stderr: thrown in /netsession.net/httpdocs/inc/Classes/DB.php on line 213, referer: https://netsession.net/				Apache-Fehler
```

![image](https://github.com/lansuite/lansuite/assets/20731374/19e99d76-989e-410f-8965-f386153d9c1d)

**Comment by Pimmal** [comment]
Seems these errors are gone now.

**Comment by M4LuZ** [comment]
That's great to hear, happy to help!
