### ISSUE TITLE
lansuite über FTP installieren?

### ISSUE THREAD

**Issue by fritzdanny** [lansuite/lansuite#450]
Hallo!

Ich habe bei 1und1 einen FTP Server + Domain, gibt es eine Möglichkeit hier lansuite zu installieren?

**Comment by M4LuZ** [comment]
Moin @fritzdanny,

du meinst wahrscheinlich, dass du Webspace bei 1&1, über den du nur per FTP zugreifen kannst, korrekt?
Das geht generell und der häufigste Anwendungsfall, allerdings ist genau der leider noch nicht in der Doku. Ich schreibe da mal was zu.
Wie viel Kenntnis hast du denn mit Linux-Systemen?

**Comment by fritzdanny** [comment]
hallo M4LUZ :)

ja nur per FTP!

Danke :)

Linux leider eher weniger.

**Comment by fritzdanny** [comment]
Hallo!

Ganz verstehe ich noch nicht.
Ich habe die Daten auf dem FTP Server, aber was muss ich dann genau machen?

**Comment by fritzdanny** [comment]
@M4LuZ

**Comment by fritzdanny** [comment]
@M4LuZ Kannst du mir hier noch helfen bitte?

**Comment by fritzdanny** [comment]
@PhilmacFLy @mre @andygrunwald @M4LuZ 
Ich habe die Daten über FTP auf den Server gelegt, aber wie muss ich jetzt genau weitermachen?

**Comment by M4LuZ** [comment]
> Ich habe die Daten über FTP auf den Server gelegt, aber wie muss ich jetzt genau weitermachen?

Folgende Schritte sind zu erledigen:
1. Erwartungshaltung zurückschrauben.
 LanSuite bekommt aktuell nur die nötigste Wartung und Support. Reaktionszeiten sind dementsprechend lang. Besonders da es wichtigere Themen gibt, die sich leider auch wenig bewegen.
2. Lesen. Wie oben erwähnt existiert keine Dokumentation für diesen Fall und muss erst geschrieben werden. Bei eingehender Betrachtung dieses Tickets siehst du auch, dass zwei Änderungen bereits zu diesem Thema hochgeladen wurden.
3. Informieren. Was zu tun ist, entspricht dem üblichen bei Projekten, die Composer verwenden. Generell ist angeraten, als Veranstalter Know-How in den verschiedenen Bereichen (Strom, Netzwerk, Infrastruktur, Gameserver, Orga, Rechtliches und Finanzielles) vorzuhalten. Die Fähigkeit, sein Inter/Intranetsystem administrieren zu können, ist elementar wichtig, um bei Problemen reagieren zu können.
4. Neue Doku testen!
Nachdem ich das alles losgeworden bin, kann ich aber sagen, dass jetzt ein erster Wurf einer entsprechenden Dokumentation hier existiert: https://lansuite.github.io/lansuite/docs/installation.html
Auch dort sind die Schritte nicht bis ins kleinste beschrieben, daher wäre ich für Feedback dankbar, ob das auf dem Niveau OK ist, oder wir noch mehr in die Tiefe gehen müssen.

**Comment by duke3dexe** [comment]
Hallo M4LuZ,

ich habe PHP, natürlich 8.0 runtergeladen und nun meckert der composer, dass er PHP 7.0 sehen will.

Was nun? 

ps: früher war lansuite einfacher zu installieren :/

**Comment by Dwarfex** [comment]
Hi @duke3dexe, 
momentan läuft lansuit nur auf PHP 7.* - (8.0 ist noch sehr neu - erst am 30.11.2020 released).
Um lansuite "einfacher" zu installieren existiert bereits ein Ticket (https://github.com/lansuite/lansuite/issues/451).

Solltest du aber nur die Dateien (z.B. lokal) generieren wollen um sie später auf einen Webhosting Server legen zu können, dan hilft dir vielleicht dieser Composer Befehl:

`composer install --ignore-platform-reqs` anstelle des "normalen" 'composer install'



P.S.: Sie es als Teamleistung ;) - alles was dir auffällt, kann man in die Dokumentation übernehmen, um den Prozess zu verbessern oder anderen nach dir Helfen zu können :)

**Comment by duke3dexe** [comment]
Hi @Dwarfex, 

Files wurden erstellt, alles schön grün. Aber nach dem Aufruf der install auf der lokalen Maschine kam:

`Fatal error: Uncaught Error: Call to undefined function dependencyPreCheck() in C:\Apache24\htdocs\ls\install.php:7 Stack trace: #0 {main} thrown in C:\Apache24\htdocs\ls\install.php on line 7`

bzw der Index:

`Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in C:\Apache24\htdocs\ls\index.php:230 Stack trace: #0 {main} thrown in C:\Apache24\htdocs\ls\index.php on line 230`

Suchmaschine meines Vertrauens hat ergeben, dass get_magic_quotes_gpc() ab PHP 7.4 nicht mehr existiert.

> Es ist zu beachten, dass der Versuch magic_quotes_gpc zur Laufzeit zu setzen, nicht funktioniert. 
https://www.php.net/manual/de/function.get-magic-quotes-gpc.php

Tja ...

PS: eine lansuite 5.0 wäre schon praktisch, aber da finde ich nichts. :D Und gerne teste ich weiter. Ist sozusagen mein Job.

**Comment by andygrunwald** [comment]
@duke3dexe Ich habe eine kleine Anpassung bez. deines Fehlers in https://github.com/lansuite/lansuite/pull/465 gemacht. Schau dir doch mal die geänderte Datei an https://github.com/lansuite/lansuite/pull/465/files überführe die in deine Installation und ob es den Fehler behebt.

**Comment by duke3dexe** [comment]
Die Install.php ist aber noch nicht gelaufen, nur zur Info.

Ich habe also die Zeile
`f (!get_magic_quotes_gpc()) {`
 
auskommentiert zu:

`//if (!get_magic_quotes_gpc()) {
// TODO Remove this get_magic_quotes_gpc function check, once this project had 7.4 as a minimum requirement.
// See
//	- Setting: https://www.php.net/manual/en/info.configuration.php#ini.magic-quotes-gpc
//	- Function: https://www.php.net/manual/en/function.get-magic-quotes-gpc.php
if (!function_exists('get_magic_quotes_gpc') || !get_magic_quotes_gpc()) {`


aber ....


Fatal error: Uncaught TypeError: mysqli_real_escape_string(): Argument #1 ($mysql) must be of type mysqli, bool given in C:\Apache24\htdocs\ls\inc\Classes\DB.php:93 Stack trace: #0 C:\Apache24\htdocs\ls\inc\Classes\DB.php(93): mysqli_real_escape_string(false, 'LS Error: PHP W...') #1 [internal function]: LanSuite\DB->escape(Array) #2 C:\Apache24\htdocs\ls\inc\Classes\DB.php(198): preg_replace_callback('#(%string%|%int...', Array, '\n IN...') #3 C:\Apache24\htdocs\ls\inc\Classes\Func.php(688): LanSuite\DB->qry('\n IN...', NULL, 'LS Error: PHP W...', 3, 'LS-Fehler', '', '/ls/', 'index.php', '127.0.0.1') #4 C:\Apache24\htdocs\ls\inc\Classes\Func.php(319): LanSuite\Func->log_event('LS Error: PHP W...', 3, 'LS-Fehler') #5 C:\Apache24\htdocs\ls\index.php(441): LanSuite\Func->error('PHP Warning: my...') #6 {main} thrown in C:\Apache24\htdocs\ls\inc\Classes\DB.php on line 93

**Comment by andygrunwald** [comment]
> Die Install.php ist aber noch nicht gelaufen, nur zur Info.

Das ist nicht schlimm, weil die install.php die index.php inkludiert. Siehe https://github.com/lansuite/lansuite/blob/master/install.php#L14

Der Fehler liest sich so, als kann keine Verbindung zur Datenbank aufgebaut werden.
Hast du dein Konfigurationsfile überprüft? Siehe https://lansuite.github.io/lansuite/docs/configuration.html

**Comment by duke3dexe** [comment]
okay, das habe ich verschlafen.

Ich habe die Angaben aus deinem Link ergänzt und genau so in eine config.php unter inc\base\ gespeichert.

Aber:

`Fatal error: Uncaught TypeError: mysqli_real_escape_string(): Argument #1 ($mysql) must be of type mysqli, bool given in C:\Apache24\htdocs\ls\inc\Classes\DB.php:93 Stack trace: #0 C:\Apache24\htdocs\ls\inc\Classes\DB.php(93): mysqli_real_escape_string(false, 'LS Error: PHP W...') #1 [internal function]: LanSuite\DB->escape(Array) #2 C:\Apache24\htdocs\ls\inc\Classes\DB.php(198): preg_replace_callback('#(%string%|%int...', Array, '\n IN...') #3 C:\Apache24\htdocs\ls\inc\Classes\Func.php(688): LanSuite\DB->qry('\n IN...', NULL, 'LS Error: PHP W...', 3, 'LS-Fehler', '', '/ls/', 'index.php', '127.0.0.1') #4 C:\Apache24\htdocs\ls\inc\Classes\Func.php(319): LanSuite\Func->log_event('LS Error: PHP W...', 3, 'LS-Fehler') #5 C:\Apache24\htdocs\ls\index.php(441): LanSuite\Func->error('PHP Warning: Un...') #6 {main} thrown in C:\Apache24\htdocs\ls\inc\Classes\DB.php on line 93`


bzw mit debugmode = 1

![grafik](https://user-images.githubusercontent.com/77051775/104104289-6d32e480-52a7-11eb-9fb0-7ae067e8389e.png)

**Comment by andygrunwald** [comment]
@duke3dexe Wir nähern uns.
Eine kurze Frage: Welche PHP Version hast du nun im Endeffekt laufen?

Und kannst du mal bitte in der index.php in Zeile 293, die Zeile

```php
if ($config['environment']['configured'] == 0) {
```

mit folgendem ersetzen

```php
if (!array_key_exists('environment', $config) || $config['environment']['configured'] == 0) {
```

**Comment by duke3dexe** [comment]
Whoops

![grafik](https://user-images.githubusercontent.com/77051775/104132388-447d1e80-537d-11eb-852c-8e2672641957.png)


Ich habe PHP 8.0.0 laufen :P

**Comment by andygrunwald** [comment]
@duke3dexe LANSuite unterstützt zur Zeit noch kein PHP 8.
Gerne nehmen wir Pull Requests dafür entgegen, doch leider fehlt uns etwas die Zeit. Sorry.

**Comment by duke3dexe** [comment]
Ja, blöd. Kann ich nachvollziehen. :/
